//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AccountNumber { get; set; }
        public int MemberId { get; set; }
        public int AccountTypeId { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string AccountStatusCode { get; set; }
        public bool Overdraft { get; set; }
    
        public virtual AccountStatus AccountStatus { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        public void Deposit(decimal amount)
        {
            this.CurrentBalance += amount;
            if(this.Overdraft && this.CurrentBalance >= 0)
            {
                this.Overdraft = false;
            }
        }

        public void Withdraw(decimal amount)
        {
            this.CurrentBalance -= amount;
        }
    }
}
