//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDeposit
    {
        public int TermDepositId { get; set; }
        public int MemberId { get; set; }
        public decimal Amount { get; set; }
        public int Duration_Months { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
